[workspace]
resolver = "3"
members = [
    "clients",
    "desktop",
    "schemas",
    "storage"
]

[workspace.package]
edition = "2024"
version = "0.1.14-pre"
authors = ["Venus Xeon-Blonde"]
homepage = "https://oshibana.cards"
repository = "https://github.com/vcfxb/oshibana"
license = "MIT"

[workspace.dependencies]
schemas = { path = "schemas" }
clients = { path = "clients" }
storage = { path = "storage" }
chrono = { version = "0.4.45", features = ["serde"] }
polars  = { version = "0.54.4", features = [
    "dtype-struct",
    "strings",
    "dtype-i128",
    "dtype-u128",
    "dtype-u8",
    "lazy",
    "parquet",
    "regex",
    "is_in"
]}

futures = "0.3.32"
reqwest = { version = "0.13.4", features = ["json", "blocking"] }
url = { version = "2.5.8", features = ["serde"] }
serde = "1"
uuid = { version = "1.23.4", features = ["v4"] }
scopeguard = "1.2.0"
serde_json = "1"
atomic_float = "1.1.0"
atomic-time = "0.2.1"
tokio = { version = "1.52", features = ["full"] }
log = "0.4"
anyhow = "1"
thiserror = "2.0.18"
humansize = "2.1.3"
strum = { version = "0.28.0", features = ["derive"] }
heck = "0.5.0"
