[workspace]
resolver = "3"
members = [
    "clients",
    "desktop",
    "schemas"
]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
schemas = { path = "schemas" }
clients = { path = "clients" }
#new_chrono  = { package = "chrono", version = "0.4.44", features = ["serde"] }
# needed to compile polars I guess? https://github.com/pola-rs/polars/issues/26577
chrono = { version = "=0.4.41", features = ["serde"] }

polars  = { version = "0.53.0", features = [
    "dtype-struct",
    "dtype-i128",
    "dtype-u128",
    "lazy",
    "parquet"
]}

futures = "0.3.32"
reqwest = { version = "0.13.2", features = ["json", "blocking"] }
url = { version = "2.5.8", features = ["serde"] }
serde = "1.0.228"
