
WHITESPACE = _{ WHITE_SPACE }

identifier = @{ XID_START ~ XID_CONTINUE* }

operator = @{ "<=" | ">=" | "!=" | "=" | "<" | ">" | ":" }

string_char = _{
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "'" | "n" | "r" | "t")
    | "\\" ~ ("u{" ~ ASCII_HEX_DIGIT{4, 6} ~ "}")
}

string_inner = @{ string_char* }
string = ${ "\"" ~ string_inner ~ "\"" }

regex_inner = @{ (!"/" ~ ANY)+ }
regex = ${ "/" ~ regex_inner ~ "/" }

number = @{
    "-"?
    ~ ("0" | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*)
    ~ ("." ~ ASCII_DIGIT*)?
    ~ (^"e" ~ ("+" | "-")? ~ ASCII_DIGIT+)?
}

lang_directive        = _{ ^"lang" | ^"language" }
lang_value_english    = { ^"english" | ^"eng" | ^"en" }
lang_value_spanish    = { ^"spanish" | ^"es" }
lang_value_french     = { ^"french" | ^"fr" }
lang_value_german     = { ^"german" | ^"deutsch" | ^"de" }
lang_value_italian    = { ^"italian" | ^"it" }
lang_value_portuguese = { ^"portuguese" | ^"pt" }
lang_value_japanese   = { ^"japanese" | ^"ja" | ^"jp" }
lang_value_korean     = { ^"korean" | ^"kr" | ^"ko" }
lang_value_russian    = { ^"russian" | ^"ru" }
lang_value_zhs        = { ^"zhs" }
lang_value_zht        = { ^"zht" }
lang_value_hebrew     = { ^"hebrew" | ^"he" }
lang_value_latin      = { ^"latin" | ^"la" }
lang_value_grc        = { ^"grc" }
lang_value_arabic     = { ^"arabic" | ^"ar" }
lang_value_sanskrit   = { ^"sanskrit" | ^"sa" }
lang_value_phyrexian  = { ^"Phyrexian" | ^"ph" }
lang_value_quenya     = { ^"Quenya" | ^"qya" }

lang_value = {
    lang_value_english
    | lang_value_spanish
    | lang_value_french
    | lang_value_german
    | lang_value_italian
    | lang_value_portuguese
    | lang_value_japanese
    | lang_value_korean
    | lang_value_russian
    | lang_value_zhs
    | lang_value_zht
    | lang_value_hebrew
    | lang_value_latin
    | lang_value_grc
    | lang_value_arabic
    | lang_value_sanskrit
    | lang_value_phyrexian
    | lang_value_quenya
}

lang_filter = ${
    lang_directive ~
    ("=" | ":") ~
    lang_value
}

name_directive = _{ ^"name" }
name_operator = { "!=" | ":" | "=" }
name_filter = ${ name_directive ~ name_operator ~ filter_value }

optionally_exact_filter_no_directive = ${ "!"? ~ filter_value }

filter = {
    lang_filter
    | name_filter
    | optionally_exact_filter_no_directive
}

filter_value = { string | regex | identifier }

modifier = { "-" }

group = { "(" ~ union ~ ")" }

item = ${ modifier? ~ (group | filter) }

intersection = { item ~ ((WHITESPACE+ ~ "and" ~ WHITESPACE+)? ~ item)* }

union = { intersection ~ (WHITESPACE+ ~ "or" ~ WHITESPACE+ ~ intersection)* }

query = { SOI ~ union ~ EOI }
