[package]
name = "storage"
edition.workspace = true
version.workspace = true

[features]
scryfall-sync-tests = []

[dependencies]
# Oshibana Crates
schemas.workspace = true
clients.workspace = true

# Common Dependencies
# Error Handling
anyhow.workspace = true
log.workspace = true
thiserror.workspace = true

# Atomics
atomic-time.workspace = true

# Datatypes
chrono.workspace = true
url.workspace = true

# Serialization
serde_json.workspace = true
serde.workspace = true
struson = { version = "0.7.2", features = ["serde"] }

# Compression
flate2 = "1.1.9"

# Parsing
unescape_zero_copy = "2.3.2"

# Utilities
polars.workspace = true
tokio.workspace = true
scopeguard.workspace = true
reqwest.workspace = true
humansize.workspace = true
directories = "6.0.0"
