[package]
name = "schemas"
version = "0.1.0"
edition = "2024"

[dependencies]
enumflags2 = { version = "0.7.12", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
uuid = { version = "1.23.1", features = ["serde"] }
strum = { version = "0.28.0", features = ["derive"] }
typename = "0.1.2"

# Workspace deps
chrono.workspace = true
polars.workspace = true
url.workspace = true
paste = "1.0.15"
sealed = "0.6.0"
