name: cargo
on: ["push", "pull_request"]

# Cancel in-progress runs for previous commits if there are any that haven't completed yet.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Oshibana source
        uses: actions/checkout@v7

      # Use stable Rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo test
