[package]
name = "desktop"
edition.workspace = true
version.workspace = true

[[bin]]
name = "oshibana"
path = "src/main.rs"

[features]
prod = []

[dependencies]
# Workspace crates
clients.workspace = true
schemas.workspace = true
storage.workspace = true

# Atomics
atomic_float.workspace = true
atomic-time.workspace = true

# Error handling
anyhow.workspace = true
log.workspace = true
log4rs = "1.4.0"

# Datatypes
chrono.workspace = true

# Utilities
polars.workspace = true
tokio.workspace = true
mimalloc = "0.1.50"
strum.workspace = true

# Formatting
humansize.workspace = true
heck.workspace = true

# UI
opener = { version = "0.8.4", features = ["reveal"] }

# Disabling wgpu and using glow speeds up startup significantly (2 seconds).
# This seems to be due to wgpu taking time to query the OS for gpu adapter data and the host responding too slowly?
# not sure if this is a wgpu issue or a driver issue or maybe just something on my system, but glow should be fine
# for most/all usecases regardless
eframe = { version = "0.34.2", default-features = false, features = [
    "glow",
    "wayland",
    "default_fonts",
    "x11",
    "persistence"
] }

egui = "0.34.1"
egui_extras = { version = "0.34.3", features = ["all_loaders", "http", "file"] }
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
egui_material_icons = "0.6.0"
egui_alignments = "0.3.8"
